
var SCALE_IMG_CONST = 0.35;
var KEY_LEFT = 37;
var KEY_RIGHT = 39;
var SPEED_MOVE = 3;
var FRICTION = 0.8;

var OBSTACLE_INTERVAL = 200;
var OBSTACLE_SPEED_MOVE = 1;

var COIN_INTERVAL = 50;

var DRAW_INTERVAL_MS = 1000 / 60;